### ISSUE TITLE
AJAX Conflicts

### ISSUE THREAD

**Issue by cehwitham** [sanchothefat/wp-less#44]
When using your WP Less code as part of a theme and including wp-less.php in my functions.php file, the LESS processing works a treat but it causes lots of AJAX issues when adding menu items, updating widget settings, quick editing categories etc. Basically anything that uses an AJAX call (I think) is just hanging with the loading wheel shown indefinitely. Removing wp-less.php stops the issue and everything works fine.

**Comment by sanchothefat** [comment]
I'd check if this happens with the above plugins and a different theme, not sure what genesis might be doing in addition.

Reopen if you need to. Should probably be using grunt/gulp by now though :stuck_out_tongue:
