### ISSUE TITLE
Use WP-LESS in my plugin

### ISSUE THREAD

**Issue by fakingfantastic** [sanchothefat/wp-less#60]
It would be awesome if I could do something like...

```php
add_action( 'wp_head', 'my_plugin_head' );

function my_plugin_head() {
  wp_enqueue_style(
    'my-plugin-foo',
    plugin_dir_url(__FILE__) . 'my-plugin-foo.less'
  );  
}
```

.. and the WP-LESS parser would kick in, allowing me to use LESS in my internal plugins (I would add WP-LESS as a dependency to my plugin as well)

Let me know, thanks!

**Comment by sanchothefat** [comment]
- Is this going to update my CSS files automatically?
  - yes
- Is it possible to build not-minified AND minified CSS files separately?
  - no not separately, you can modify how the lessc class does stuff though via an action
- Is this event (writing the CSS files) handled by Wordpress?
  - yes
- Does this happen when I save the theme options or it just detects changes in the variable file and re-writes the CSS files?
  - if the vars passed in to the filter change then it will recompile the css
- Can I setup several LESS files to be handled by your script or just one?
  - as many as you like :) You can also use @ import
- Can I combine several LESS files to create a ONE CSS file minified output?
  - yes

If you need any further advice reopen the issue.
