### ISSUE TITLE
wp-less-cache breaks relative URLs

### ISSUE THREAD

**Issue by dantman** [sanchothefat/wp-less#65]
I'm using wp-less in a theme and expected that I could do a `url(images/foo.png)` as normal with less and css. However because the compiled css is moved to `/wp-content/uploads/wp-less-cache/` and the `url()` is left as-is the path become broken.

**Comment by sanchothefat** [comment]
Not something I can fix easily due the servers side compile so variables is the way to do it with this plugin. Sorry!
