### ISSUE TITLE
Package not in packagist

### ISSUE THREAD

**Issue by Soullivaneuh** [sanchothefat/wp-less#69]
Your package aren't in packagist.

So if I add it to my composer.json file, I have the following error:

```
  Problem 1
    - The requested package icit/wp-less could not be found in any version, there may be a typo in the package name.
```

You can add it here: https://packagist.org/packages/submit

Thanks.

**Comment by sanchothefat** [comment]
under icit/wp-less :)

**Comment by Soullivaneuh** [comment]
:+1:
